### ISSUE TITLE
Bar appears after clicking play (screenshot, gif)

### ISSUE THREAD

**Issue by gordykeene** [EnigmaDragons/LDJam46#411]
If this is a "loading bar"(?) it doesn't feel right.

![2020-04-20_06h41_38.png](https://zube.io/files/enigmadragons/6c216ceca02f02d50f6361f8092fe7cf-2020-04-20_06h41_38.png)

![2020-04-20_06h35_59.gif](https://zube.io/files/enigmadragons/d216977a84cc7da932b04292ab46438e-2020-04-20_06h35_59.gif)

**Comment by jerry411** [comment]
It is, in fact, loading bar. But because of bug in Unity, game freezes on SceneManager.LoadSceneAsync and it immediately loads after that.
